name: CMake

on: [pull_request]

jobs:
  build:
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install rdma  
      run: |
          echo $(pwd) &&
          wget -nv -O /tmp/rdma-core.tar.gz https://github.com/linux-rdma/rdma-core/archive/refs/tags/v44.0.tar.gz   
          cd /tmp && tar xzf rdma-core.tar.gz && 
          cd rdma-core-44.0/ && 
          mkdir -p ./build && cd build && cmake ../ && sudo make && sudo  make install && echo $(pwd) && ls * && 
          ls /usr/local/lib/libg* && ls /usr/local/include/gtest &&  
          echo "rdma installed ok" 
    - name: cmake and build 
      run: |
         echo $(pwd) &&  cd ./disni/libdisn && sh ./build.sh      

