name: CMake

on: [push, pull_request]

jobs:
  build:
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependency libs 
      run: |
          echo "install dependnecy libraries"
          sudo apt-get install libnl-route-3-dev libnl-3-dev
    - name: Install rdma  
      run: |
          echo $(pwd) &&
          wget -nv -O /tmp/rdma-core.tar.gz https://github.com/linux-rdma/rdma-core/archive/refs/tags/v44.0.tar.gz   
          cd /tmp && tar xzf rdma-core.tar.gz && 
          cd rdma-core-44.0/ && 
          ls && 
          sudo ./build.sh && 
          echo "rdma installed ok" 
    - name: cmake and build 
      run: |
         echo $(pwd) &&  cd ./disni/libdisn && sh ./build.sh      

